# Generated by Django 4.2.7 on 2023-12-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='sender',
        ),
    ]
