# Generated by Django 4.2.7 on 2023-12-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_remove_request_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='sem',
            field=models.CharField(default='sem 3', max_length=100),
            preserve_default=False,
        ),
    ]
