# Generated by Django 4.2.7 on 2023-12-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_request_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='body',
            field=models.TextField(default='body of letter'),
            preserve_default=False,
        ),
    ]
