# Generated by Django 4.2.7 on 2023-12-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_request_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='frequest',
        ),
    ]
