# Generated by Django 4.2.7 on 2024-01-30 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faculty', '0006_rename_frequest_mfrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfrequest',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mfrequest',
            name='permitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mfrequest',
            name='remarks',
            field=models.TextField(default='NO REMARKS'),
        ),
        migrations.AddField(
            model_name='mfrequest',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
