# Generated by Django 4.2.7 on 2024-01-31 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faculty', '0008_mfrequest_reciver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfrequest',
            name='reciver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HOD', to=settings.AUTH_USER_MODEL),
        ),
    ]
